sudo: false
language: node_js
node_js:
- '0.12'
- '0.10'
- node
deploy:
  provider: npm
  email: mike@cousins.io
  api_key:
    secure: UZU7z/ksH/ZT6FdX85xOapN8qx4/T8Ub3VZmiZXdJ3e43J0XX1wT/SXL62cf1+45TK+vaL1Oi3bbX7f7ESph6THPU4SxIVWZTrc1z0kdVqXFMgtzBhYXg0VTWXYpFy6eoTtsp5TOxHQtRX/Ftr9lJEasue9antgsYuAaNc9D0xQ=
  on:
    node: node
    tags: true
    all_branches: true
